version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    env_file:
      - .env

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
